language: cpp
compiler: gcc

before_install:
        - sudo apt-get install libsfml-dev

script: 
        - cd Sea_battles/
        - ./autorun.sh DEBUG
        - ./autorun.sh

notifications:
        email:
                - uslon@yahoo.com
 

