language: cpp
compiler: gcc

script: 
        - cd Sea_battles/
        - cmake CMakeLists.txt
        - make
        - ./Sea_battles

notifications:
        email:
                - uslon@yahoo.com
 

